//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynthExport.PhotosynthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://labs.live.com/", ConfigurationName="PhotosynthService.PhotosynthServiceSoap")]
    public interface PhotosynthServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/CreatePanorama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.CreateCollectionResult CreatePanorama(string Name, string Tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/AddPanoramaPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.AddPhotoResult AddPanoramaPhoto(System.Guid PanoramaId, string FileId, int FileChunkCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/CommitPanorama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.CommitResult CommitPanorama(System.Guid PanoramaId, string Manifest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/CancelPanorama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result CancelPanorama(System.Guid PanoramaId, int Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/CreateSynth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.CreateCollectionResult CreateSynth(string Name, string Tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/AddSynthPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.AddPhotoResult AddSynthPhoto(System.Guid CollectionId, string ImageHash, string PhotoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/CommitSynth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.CommitResult CommitSynth(System.Guid CollectionId, string Manifest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/CancelSynth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result CancelSynth(System.Guid CollectionId, int Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/GetServerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.ServerInfo GetServerInfo(string ClientVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/IsClientUpdateRequired", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result IsClientUpdateRequired(out string DownloadUrl, string ClientVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/GetUserStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result GetUserStatus(out string UserStatus, out long StorageQuota, out long StorageConsumption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/RevertEdit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result RevertEdit(System.Guid CollectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/ReportUploadStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ReportUploadStatus(int statusCode, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/GetCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.PhotosynthResponse GetCollection(string collectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/GetCollectionStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result GetCollectionStatus(System.Guid collectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/GetCollectionData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.CollectionResult GetCollectionData(System.Guid collectionId, bool incrementEmbedCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/IncrementSynthViewCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void IncrementSynthViewCount(string collectionId, SynthExport.PhotosynthService.ViewType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/DeleteGeotag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.Result DeleteGeotag(System.Guid collectionId, bool alignmentOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/RefreshService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.LiveLabsResponse RefreshService(string applicationGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.live.com/GetWebServiceStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SynthExport.PhotosynthService.LiveLabsResponse GetWebServiceStats(string applicationGuid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class CreateCollectionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private System.Guid collectionIdField;
        
        private string uploadUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid CollectionId {
            get {
                return this.collectionIdField;
            }
            set {
                this.collectionIdField = value;
                this.RaisePropertyChanged("CollectionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UploadUrl {
            get {
                return this.uploadUrlField;
            }
            set {
                this.uploadUrlField = value;
                this.RaisePropertyChanged("UploadUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public enum Result {
        
        /// <remarks/>
        InvalidPuidFormat,
        
        /// <remarks/>
        CannotFindCollection,
        
        /// <remarks/>
        CannotFindUser,
        
        /// <remarks/>
        MalformedManifest,
        
        /// <remarks/>
        MissingCollectionEntry,
        
        /// <remarks/>
        EncounteredUnaccountedFile,
        
        /// <remarks/>
        CollectionAlreadyExists,
        
        /// <remarks/>
        AlreadyCommittedCollection,
        
        /// <remarks/>
        AuthenticationError,
        
        /// <remarks/>
        UnknownError,
        
        /// <remarks/>
        UploadsAreDisabled,
        
        /// <remarks/>
        CannotProcessCollection,
        
        /// <remarks/>
        UserQuotaExceededTheLimit,
        
        /// <remarks/>
        NotCollectionOwner,
        
        /// <remarks/>
        NotLoggedIn,
        
        /// <remarks/>
        InvalidSynthData,
        
        /// <remarks/>
        SynthEditsAreDisabled,
        
        /// <remarks/>
        InvalidArgument,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        CollectionIsAvailable,
        
        /// <remarks/>
        CollectionIsDeleted,
        
        /// <remarks/>
        CollectionIsProcessing,
        
        /// <remarks/>
        CollectionIsAvailableWithoutTags,
        
        /// <remarks/>
        CollectionIsProcessingWithoutTags,
        
        /// <remarks/>
        CollectionNotEdited,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class GeoInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double latitudeField;
        
        private double longitudeField;
        
        private int zoomLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ZoomLevel {
            get {
                return this.zoomLevelField;
            }
            set {
                this.zoomLevelField = value;
                this.RaisePropertyChanged("ZoomLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class GeoAlignment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double latitudeField;
        
        private double longitudeField;
        
        private byte zoomLevelField;
        
        private float scaleField;
        
        private int altitudeDeltaField;
        
        private float rotationField;
        
        private float alignmentCtrRadiusField;
        
        private float alignmentCtrOffsetXField;
        
        private float alignmentCtrOffsetYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public byte ZoomLevel {
            get {
                return this.zoomLevelField;
            }
            set {
                this.zoomLevelField = value;
                this.RaisePropertyChanged("ZoomLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
                this.RaisePropertyChanged("Scale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int AltitudeDelta {
            get {
                return this.altitudeDeltaField;
            }
            set {
                this.altitudeDeltaField = value;
                this.RaisePropertyChanged("AltitudeDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float Rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
                this.RaisePropertyChanged("Rotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float AlignmentCtrRadius {
            get {
                return this.alignmentCtrRadiusField;
            }
            set {
                this.alignmentCtrRadiusField = value;
                this.RaisePropertyChanged("AlignmentCtrRadius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float AlignmentCtrOffsetX {
            get {
                return this.alignmentCtrOffsetXField;
            }
            set {
                this.alignmentCtrOffsetXField = value;
                this.RaisePropertyChanged("AlignmentCtrOffsetX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float AlignmentCtrOffsetY {
            get {
                return this.alignmentCtrOffsetYField;
            }
            set {
                this.alignmentCtrOffsetYField = value;
                this.RaisePropertyChanged("AlignmentCtrOffsetY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class CollectionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private CollectionType collectionTypeField;
        
        private string dzcUrlField;
        
        private string jsonUrlField;
        
        private string collectionRootField;
        
        private PrivacyLevel privacyLevelField;
        
        private GeoAlignment geoAlignmentField;
        
        private GeoInfo geoPushPinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CollectionType CollectionType {
            get {
                return this.collectionTypeField;
            }
            set {
                this.collectionTypeField = value;
                this.RaisePropertyChanged("CollectionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DzcUrl {
            get {
                return this.dzcUrlField;
            }
            set {
                this.dzcUrlField = value;
                this.RaisePropertyChanged("DzcUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JsonUrl {
            get {
                return this.jsonUrlField;
            }
            set {
                this.jsonUrlField = value;
                this.RaisePropertyChanged("JsonUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CollectionRoot {
            get {
                return this.collectionRootField;
            }
            set {
                this.collectionRootField = value;
                this.RaisePropertyChanged("CollectionRoot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PrivacyLevel PrivacyLevel {
            get {
                return this.privacyLevelField;
            }
            set {
                this.privacyLevelField = value;
                this.RaisePropertyChanged("PrivacyLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public GeoAlignment GeoAlignment {
            get {
                return this.geoAlignmentField;
            }
            set {
                this.geoAlignmentField = value;
                this.RaisePropertyChanged("GeoAlignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public GeoInfo GeoPushPin {
            get {
                return this.geoPushPinField;
            }
            set {
                this.geoPushPinField = value;
                this.RaisePropertyChanged("GeoPushPin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public enum CollectionType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Synth,
        
        /// <remarks/>
        Panorama,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public enum PrivacyLevel {
        
        /// <remarks/>
        Public,
        
        /// <remarks/>
        Unlisted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong userIdField;
        
        private System.Guid guidField;
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class PhotosynthImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid collectionIdField;
        
        private string photoUrlField;
        
        private string featuresUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid CollectionId {
            get {
                return this.collectionIdField;
            }
            set {
                this.collectionIdField = value;
                this.RaisePropertyChanged("CollectionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhotoUrl {
            get {
                return this.photoUrlField;
            }
            set {
                this.photoUrlField = value;
                this.RaisePropertyChanged("PhotoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FeaturesUrl {
            get {
                return this.featuresUrlField;
            }
            set {
                this.featuresUrlField = value;
                this.RaisePropertyChanged("FeaturesUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class PhotosynthCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PhotosynthImage[] imagesField;
        
        private int synthinessScoreField;
        
        private decimal megaPixelsField;
        
        private CollectionType collectionTypeField;
        
        private int imageCountField;
        
        private System.Guid idField;
        
        private string nameField;
        
        private string thumbnailUrlField;
        
        private System.Guid ownerUserGuidField;
        
        private string ownerFriendlyNameField;
        
        private string collectionUrlField;
        
        private System.DateTime uploadDateField;
        
        private string descriptionField;
        
        private bool isDeletedField;
        
        private PrivacyLevel privacyLevelField;
        
        private int viewingsField;
        
        private int favoriteCountField;
        
        private bool isEditedField;
        
        private string startingImageUrlField;
        
        private string collectionOriginalUrlField;
        
        private float rankField;
        
        private short rankModifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public PhotosynthImage[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
                this.RaisePropertyChanged("Images");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SynthinessScore {
            get {
                return this.synthinessScoreField;
            }
            set {
                this.synthinessScoreField = value;
                this.RaisePropertyChanged("SynthinessScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal MegaPixels {
            get {
                return this.megaPixelsField;
            }
            set {
                this.megaPixelsField = value;
                this.RaisePropertyChanged("MegaPixels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CollectionType CollectionType {
            get {
                return this.collectionTypeField;
            }
            set {
                this.collectionTypeField = value;
                this.RaisePropertyChanged("CollectionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
                this.RaisePropertyChanged("ImageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ThumbnailUrl {
            get {
                return this.thumbnailUrlField;
            }
            set {
                this.thumbnailUrlField = value;
                this.RaisePropertyChanged("ThumbnailUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid OwnerUserGuid {
            get {
                return this.ownerUserGuidField;
            }
            set {
                this.ownerUserGuidField = value;
                this.RaisePropertyChanged("OwnerUserGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OwnerFriendlyName {
            get {
                return this.ownerFriendlyNameField;
            }
            set {
                this.ownerFriendlyNameField = value;
                this.RaisePropertyChanged("OwnerFriendlyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CollectionUrl {
            get {
                return this.collectionUrlField;
            }
            set {
                this.collectionUrlField = value;
                this.RaisePropertyChanged("CollectionUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime UploadDate {
            get {
                return this.uploadDateField;
            }
            set {
                this.uploadDateField = value;
                this.RaisePropertyChanged("UploadDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
                this.RaisePropertyChanged("IsDeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public PrivacyLevel PrivacyLevel {
            get {
                return this.privacyLevelField;
            }
            set {
                this.privacyLevelField = value;
                this.RaisePropertyChanged("PrivacyLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Viewings {
            get {
                return this.viewingsField;
            }
            set {
                this.viewingsField = value;
                this.RaisePropertyChanged("Viewings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int FavoriteCount {
            get {
                return this.favoriteCountField;
            }
            set {
                this.favoriteCountField = value;
                this.RaisePropertyChanged("FavoriteCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsEdited {
            get {
                return this.isEditedField;
            }
            set {
                this.isEditedField = value;
                this.RaisePropertyChanged("IsEdited");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string StartingImageUrl {
            get {
                return this.startingImageUrlField;
            }
            set {
                this.startingImageUrlField = value;
                this.RaisePropertyChanged("StartingImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CollectionOriginalUrl {
            get {
                return this.collectionOriginalUrlField;
            }
            set {
                this.collectionOriginalUrlField = value;
                this.RaisePropertyChanged("CollectionOriginalUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public float Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public short RankModifier {
            get {
                return this.rankModifierField;
            }
            set {
                this.rankModifierField = value;
                this.RaisePropertyChanged("RankModifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class ResponseError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string detailMessageField;
        
        private string errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DetailMessage {
            get {
                return this.detailMessageField;
            }
            set {
                this.detailMessageField = value;
                this.RaisePropertyChanged("DetailMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhotosynthResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class LiveLabsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseDataField;
        
        private ResponseError[] errorsField;
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
                this.RaisePropertyChanged("ResponseData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Order=1)]
        public ResponseError[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class PhotosynthResponse : LiveLabsResponse {
        
        private PhotosynthCollection[] collectionsField;
        
        private UserInfo[] usersField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public PhotosynthCollection[] Collections {
            get {
                return this.collectionsField;
            }
            set {
                this.collectionsField = value;
                this.RaisePropertyChanged("Collections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public UserInfo[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
                this.RaisePropertyChanged("Users");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class ServerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private int maxUploadSizeField;
        
        private int recommendUploadSizeField;
        
        private string syntherDownloadUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxUploadSize {
            get {
                return this.maxUploadSizeField;
            }
            set {
                this.maxUploadSizeField = value;
                this.RaisePropertyChanged("MaxUploadSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RecommendUploadSize {
            get {
                return this.recommendUploadSizeField;
            }
            set {
                this.recommendUploadSizeField = value;
                this.RaisePropertyChanged("RecommendUploadSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SyntherDownloadUrl {
            get {
                return this.syntherDownloadUrlField;
            }
            set {
                this.syntherDownloadUrlField = value;
                this.RaisePropertyChanged("SyntherDownloadUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class CommitResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public partial class AddPhotoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private string photoUrlField;
        
        private string actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PhotoUrl {
            get {
                return this.photoUrlField;
            }
            set {
                this.photoUrlField = value;
                this.RaisePropertyChanged("PhotoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://labs.live.com/")]
    public enum ViewType {
        
        /// <remarks/>
        Site,
        
        /// <remarks/>
        Embed,
        
        /// <remarks/>
        Map,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhotosynthServiceSoapChannel : SynthExport.PhotosynthService.PhotosynthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhotosynthServiceSoapClient : System.ServiceModel.ClientBase<SynthExport.PhotosynthService.PhotosynthServiceSoap>, SynthExport.PhotosynthService.PhotosynthServiceSoap {
        
        public PhotosynthServiceSoapClient() {
        }
        
        public PhotosynthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotosynthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotosynthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotosynthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SynthExport.PhotosynthService.CreateCollectionResult CreatePanorama(string Name, string Tags) {
            return base.Channel.CreatePanorama(Name, Tags);
        }
        
        public SynthExport.PhotosynthService.AddPhotoResult AddPanoramaPhoto(System.Guid PanoramaId, string FileId, int FileChunkCount) {
            return base.Channel.AddPanoramaPhoto(PanoramaId, FileId, FileChunkCount);
        }
        
        public SynthExport.PhotosynthService.CommitResult CommitPanorama(System.Guid PanoramaId, string Manifest) {
            return base.Channel.CommitPanorama(PanoramaId, Manifest);
        }
        
        public SynthExport.PhotosynthService.Result CancelPanorama(System.Guid PanoramaId, int Reason) {
            return base.Channel.CancelPanorama(PanoramaId, Reason);
        }
        
        public SynthExport.PhotosynthService.CreateCollectionResult CreateSynth(string Name, string Tags) {
            return base.Channel.CreateSynth(Name, Tags);
        }
        
        public SynthExport.PhotosynthService.AddPhotoResult AddSynthPhoto(System.Guid CollectionId, string ImageHash, string PhotoName) {
            return base.Channel.AddSynthPhoto(CollectionId, ImageHash, PhotoName);
        }
        
        public SynthExport.PhotosynthService.CommitResult CommitSynth(System.Guid CollectionId, string Manifest) {
            return base.Channel.CommitSynth(CollectionId, Manifest);
        }
        
        public SynthExport.PhotosynthService.Result CancelSynth(System.Guid CollectionId, int Reason) {
            return base.Channel.CancelSynth(CollectionId, Reason);
        }
        
        public SynthExport.PhotosynthService.ServerInfo GetServerInfo(string ClientVersion) {
            return base.Channel.GetServerInfo(ClientVersion);
        }
        
        public SynthExport.PhotosynthService.Result IsClientUpdateRequired(out string DownloadUrl, string ClientVersion) {
            return base.Channel.IsClientUpdateRequired(out DownloadUrl, ClientVersion);
        }
        
        public SynthExport.PhotosynthService.Result GetUserStatus(out string UserStatus, out long StorageQuota, out long StorageConsumption) {
            return base.Channel.GetUserStatus(out UserStatus, out StorageQuota, out StorageConsumption);
        }
        
        public SynthExport.PhotosynthService.Result RevertEdit(System.Guid CollectionId) {
            return base.Channel.RevertEdit(CollectionId);
        }
        
        public void ReportUploadStatus(int statusCode, string fileName) {
            base.Channel.ReportUploadStatus(statusCode, fileName);
        }
        
        public SynthExport.PhotosynthService.PhotosynthResponse GetCollection(string collectionId) {
            return base.Channel.GetCollection(collectionId);
        }
        
        public SynthExport.PhotosynthService.Result GetCollectionStatus(System.Guid collectionId) {
            return base.Channel.GetCollectionStatus(collectionId);
        }
        
        public SynthExport.PhotosynthService.CollectionResult GetCollectionData(System.Guid collectionId, bool incrementEmbedCount) {
            return base.Channel.GetCollectionData(collectionId, incrementEmbedCount);
        }
        
        public void IncrementSynthViewCount(string collectionId, SynthExport.PhotosynthService.ViewType type) {
            base.Channel.IncrementSynthViewCount(collectionId, type);
        }
        
        public SynthExport.PhotosynthService.Result DeleteGeotag(System.Guid collectionId, bool alignmentOnly) {
            return base.Channel.DeleteGeotag(collectionId, alignmentOnly);
        }
        
        public SynthExport.PhotosynthService.LiveLabsResponse RefreshService(string applicationGuid) {
            return base.Channel.RefreshService(applicationGuid);
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public SynthExport.PhotosynthService.LiveLabsResponse GetWebServiceStats(string applicationGuid) {
            return base.Channel.GetWebServiceStats(applicationGuid);
        }
    }
}
